version: '3'
services:
  lb:
    build:
      context: ./cidd/lb
      args:
        - XAAS_DOMAIN
    image: ${COMPOSE_PROJECT_NAME}-lb
    ports:
      - 80:80
      - 443:443
    depends_on:
      - static
  static:
    build:
      context: ./cidd/static
    image: ${COMPOSE_PROJECT_NAME}-static
  service:
  rdbms:
    build: 
      context: ./cidd/db
    image: ${COMPOSE_PROJECT_NAME}-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  graphdb:
