version: '3'

networks:
  attlas-network:

services:
  lb:
    build:
      context: ./services/lb
      args:
        - COMPOSE_PROJECT_NAME
        - LB_STATIC_CLIENT_NAME
        - LB_STATIC_CLIENT_NUM
        - LB_SERVICES_API_NAME
        - LB_SERVICES_API_NUM
        - CLIENT_PORT
        - CLIENT_PORTS
        - API_PORT
    image: ${COMPOSE_PROJECT_NAME}-lb
    networks:
      - attlas-network
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
      - ${CLIENT_PORTS}:${CLIENT_PORTS}
      - ${API_PORT}:${API_PORT}
    depends_on:
      - client
      - api
  client:
    build:
      context: ./static/client
      args:
        - CLIENT_HOSTNAME
        - CLIENT_PORT
        - CLIENT_PORTS
    image: ${COMPOSE_PROJECT_NAME}-client
    networks:
      - attlas-network
  api:
    build:
      context: ./services/api
      args:
        - API_ARTIFACT
        - API_HOSTNAME
        - API_PORT
    image: ${COMPOSE_PROJECT_NAME}-api
    networks:
      - attlas-network
    depends_on:
      - rdbms
      - graphdb
  rdbms:
    build:
      context: ./dbs/rdbms
    image: ${COMPOSE_PROJECT_NAME}-rdbms
    networks:
      - attlas-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DBS_RDBMS_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DBS_RDBMS_DATABASE}
      - MYSQL_USER=${DBS_RDBMS_USER}
      - MYSQL_PASSWORD=${DBS_RDBMS_PASSWORD}
  graphdb:
    build: 
      context: ./dbs/graphdb
    image: ${COMPOSE_PROJECT_NAME}-graphdb
    networks:
      - attlas-network
    volumes:
      - "${PROJECT_HOME}/neo4j-data:/data"
