version: '2'
services:
  web:
    build:
      context: ./devops/php
      args:
        - SERVICE_DOMAIN
    image: ${SERVICE_NAME}-web
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
  db:
    build: 
      context: ./devops/db
    image: ${SERVICE_NAME}-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
