version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=rpXD7es7cNSEmMML
    links:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=sonar
      - MYSQL_ROOT_PASSWORD=692A5Rww7Q97JwM6
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=rpXD7es7cNSEmMML
